---
# tasks file for httpd_webserver
- name: "Installing The WebServer"
  package:
          name: "{{ package_name }}"
          state: present

- name: "Copying content to the webserver"
  copy:
          content: "Hey there!!"
          dest: "/var/www/html/index.html"

- name: "Starting the webservice"
  service:
          name: "{{ service_name }}"
          state: started
          enabled: yes
